POST http://localhost:8000/ai/checkAnswers 
content-type: application/json 

{
    "response" : [
        {
            "question": "Do you have any Experience Internship done for the same role?",
            "answer": "yes I have too much and end on experience for the same role"
        } 
    ]
}